//
//  HomeViewController.swift
//  SShop
//
//  Created Nguyen Xuan on 2/17/20.
//  Copyright © 2020 Nguyen Xuan. All rights reserved.
//
//  Template generated by LinhVT - @linh.deli
//

import UIKit

class HomeViewController: UIViewController {
	var presenter: HomePresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}

extension HomeViewController: HomeViewProtocol {
    
}
