//
//  HomeViewController.swift
//  SShop
//
//  Created Nguyen Xuan on 2/17/20.
//  Copyright © 2020 Nguyen Xuan. All rights reserved.
//
//  Template generated by LinhVT - @linh.deli
//

import UIKit

class HomeViewController: UIViewController {
    
    @IBOutlet weak var tabBarView: STabBarView!
    
    var presenter: HomePresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        tabBarView.delegate = self
    }
}

extension HomeViewController: STabBarViewDelegate {
    func tabBarItemWasTapped(at: TabBarItemTag) {
        presenter?.tabBarTapped(tag: at)
    }
}

extension HomeViewController: HomeViewProtocol {
    
}
