//
//  AccountInteractor.swift
//  SShop
//
//  Created Nguyen Xuan on 2/17/20.
//  Copyright © 2020 Nguyen Xuan. All rights reserved.
//
//  Template generated by LinhVT - @linh.deli
//

import UIKit

class AccountInteractor: AccountInteractorInputProtocol {
    weak var presenter: AccountInteractorOutputProtocol?
}
