//
//  AccountPresenter.swift
//  SShop
//
//  Created Nguyen Xuan on 2/17/20.
//  Copyright © 2020 Nguyen Xuan. All rights reserved.
//
//  Template generated by LinhVT - @linh.deli
//

import UIKit

class AccountPresenter: AccountPresenterProtocol {
    
    weak private var view: AccountViewProtocol?
    var interactor: AccountInteractorInputProtocol?
    private let router: AccountWireframeProtocol

    init(view: AccountViewProtocol, interactor: AccountInteractorInputProtocol?, router: AccountWireframeProtocol) {
        self.view = view
        self.interactor = interactor
        self.router = router
    }
    
    func openLoginView() {
        router.goToLoginScene()
    }
    
    func performLogout() {
        SLoginManager.shared.logout()
    }
    
    func tabBarTapped(tag: TabBarItemTag) {
        router.switchToTab(tag)
    }
    
    func loginCompleted() {
        view?.reloadView()
    }
    
    func logoutCompleted() {
        view?.reloadView()
    }
}

extension AccountPresenter: AccountInteractorOutputProtocol {
    
}
