//
//  AccountModule.swift
//  SShop
//
//  Created Nguyen Xuan on 2/17/20.
//  Copyright © 2020 Nguyen Xuan. All rights reserved.
//
//  Template generated by LinhVT - @linh.deli
//

import UIKit

class AccountModule: AccountBuilderProtocol {

    static func build() -> UIViewController {
        let view = AccountViewController(nibName: nil, bundle: nil)
        let interactor = AccountInteractor()
        let router = AccountRouter()
        let presenter = AccountPresenter(view: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
