//
//  AccountProtocols.swift
//  SShop
//
//  Created Nguyen Xuan on 2/17/20.
//  Copyright © 2020 Nguyen Xuan. All rights reserved.
//
//  Template generated by LinhVT - @linh.deli
//

import UIKit

// MARK: - Builder
protocol AccountBuilderProtocol: class {
    static func build() -> UIViewController
}

// MARK: - Wireframe
protocol AccountWireframeProtocol {
    func goToLoginScene()
    func switchToTab(_ tag: TabBarItemTag)
}

// MARK: - Presenter
protocol AccountPresenterProtocol: class {
    var interactor: AccountInteractorInputProtocol? { get set }
    
    func openLoginView()
    func performLogout()
    func tabBarTapped(tag: TabBarItemTag)
    func loginCompleted()
    func logoutCompleted()
}

// MARK: - Interactor
protocol AccountInteractorOutputProtocol: class {
    /* Interactor -> Presenter */
}

protocol AccountInteractorInputProtocol: class {
    /* Presenter -> Interactor */
    var presenter: AccountInteractorOutputProtocol?  { get set }
}

// MARK: - View
protocol AccountViewProtocol: class {
    /* Presenter -> ViewController */
    var presenter: AccountPresenterProtocol?  { get set }
    func reloadView()
}
