//
//  AccountProtocols.swift
//  SShop
//
//  Created Nguyen Xuan on 2/17/20.
//  Copyright © 2020 Nguyen Xuan. All rights reserved.
//
//  Template generated by LinhVT - @linh.deli
//

import Foundation

// MARK: - Builder
protocol AccountBuilderProtocol: class {

}

// MARK: - Wireframe
protocol AccountWireframeProtocol: class {

}

// MARK: - Presenter
protocol AccountPresenterProtocol: class {
    var interactor: AccountInteractorInputProtocol? { get set }
}

// MARK: - Interactor
protocol AccountInteractorOutputProtocol: class {
    /* Interactor -> Presenter */
}

protocol AccountInteractorInputProtocol: class {
    /* Presenter -> Interactor */
    var presenter: AccountInteractorOutputProtocol?  { get set }
}

// MARK: - View
protocol AccountViewProtocol: class {
    /* Presenter -> ViewController */
    var presenter: AccountPresenterProtocol?  { get set }
}
