//
//  HomeProtocols.swift
//  SShop
//
//  Created Nguyen Xuan on 2/17/20.
//  Copyright © 2020 Nguyen Xuan. All rights reserved.
//
//  Template generated by LinhVT - @linh.deli
//

import Foundation

// MARK: - Builder
protocol HomeBuilderProtocol: class {

}

// MARK: - Wireframe
protocol HomeWireframeProtocol: class {
    func switchToTab(_ tag: TabBarItemTag)
}

// MARK: - Presenter
protocol HomePresenterProtocol: class {
    var interactor: HomeInteractorInputProtocol? { get set }
    func tabBarTapped(tag: TabBarItemTag)
}

// MARK: - Interactor
protocol HomeInteractorOutputProtocol: class {
    /* Interactor -> Presenter */
}

protocol HomeInteractorInputProtocol: class {
    /* Presenter -> Interactor */
    var presenter: HomeInteractorOutputProtocol?  { get set }
}

// MARK: - View
protocol HomeViewProtocol: class {
    /* Presenter -> ViewController */
    var presenter: HomePresenterProtocol?  { get set }
}
