//
//  HomePresenter.swift
//  SShop
//
//  Created Nguyen Xuan on 2/17/20.
//  Copyright © 2020 Nguyen Xuan. All rights reserved.
//
//  Template generated by LinhVT - @linh.deli
//

import UIKit

class HomePresenter: HomePresenterProtocol {
    weak private var view: HomeViewProtocol?
    var interactor: HomeInteractorInputProtocol?
    private let router: HomeWireframeProtocol

    init(view: HomeViewProtocol, interactor: HomeInteractorInputProtocol?, router: HomeWireframeProtocol) {
        self.view = view
        self.interactor = interactor
        self.router = router
    }
    
    func tabBarTapped(tag: TabBarItemTag) {
        router.switchToTab(tag)
    }
}

extension HomePresenter: HomeInteractorOutputProtocol {
    
}
