//
//  HomeRouter.swift
//  SShop
//
//  Created Nguyen Xuan on 2/17/20.
//  Copyright © 2020 Nguyen Xuan. All rights reserved.
//
//  Template generated by LinhVT - @linh.deli
//

import UIKit

class HomeRouter: HomeWireframeProtocol {
    weak var viewController: UIViewController?
    
}
