//
//  AccountDetailViewController.swift
//  SShop
//
//  Created Nguyen Xuan on 3/6/20.
//  Copyright © 2020 Nguyen Xuan. All rights reserved.
//
//  Template generated by LinhVT - @linh.deli
//

import UIKit

class AccountDetailViewController: UIViewController {
	var presenter: AccountDetailPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}

extension AccountDetailViewController: AccountDetailViewProtocol {
    
}
