//
//  LoginViewController.swift
//  SShop
//
//  Created Nguyen Xuan on 3/11/20.
//  Copyright © 2020 Nguyen Xuan. All rights reserved.
//
//  Template generated by LinhVT - @linh.deli
//

import UIKit
import CoreData
import FBSDKCoreKit
import FBSDKLoginKit
import GoogleSignIn

class LoginViewController: UIViewController {
    //MARK: - variables
    var presenter: LoginPresenterProtocol?
    
    //MARK: - life cycle
    override func viewDidLoad() {
        super.viewDidLoad()
        SLoginManager.shared.delegate = self
        navigationController?.setNavigationBarHidden(true, animated: false)
    }
    
    //MARK: - actions
    @IBAction func loginFbTapped(_ sender: UIButton) {
        print("login facebook tapped")
        presenter?.preformLogin(self, with: .facebook)
    }
    
    @IBAction func loginGgTapped(_ sender: UIButton) {
        print("google tapped")
        presenter?.preformLogin(self, with: .google)
    }
    
    @IBAction func closeButtonTapped(_ sender: UIButton) {
        presenter?.closeTapped()
    }
}

extension LoginViewController: LoginViewProtocol, LoginManagerDelegate {
    func loginDidComplete() {
        print("LOGIN did complete")
        presenter?.loginCompleted()
    }
    
    func logoutDidComplete() {
        print("logout did complete")
        // do nothing
    }
}
