//
//  LoginViewController.swift
//  SShop
//
//  Created Nguyen Xuan on 3/11/20.
//  Copyright © 2020 Nguyen Xuan. All rights reserved.
//
//  Template generated by LinhVT - @linh.deli
//

import UIKit
import CoreData
import FBSDKCoreKit
import FBSDKLoginKit
import GoogleSignIn

class LoginViewController: UIViewController {
    //MARK: - variables
    var presenter: LoginPresenterProtocol?
    weak var ssLoginManager = SSLoginManager.shared
    
    //MARK: - life cycle
    override func viewDidLoad() {
        super.viewDidLoad()
        
        ssLoginManager?.presentingViewController = self
        ssLoginManager?.delegate = self
    }
    
    //MARK: - actions
    @IBAction func loginFbTapped(_ sender: UIButton) {
        print("login facebook tapped")
        ssLoginManager?.login(with: .facebook)
    }
    
    @IBAction func loginGgTapped(_ sender: UIButton) {
        print("google tapped")
        ssLoginManager?.login(with: .google)
    }
}

extension LoginViewController: SSLoginManagerDelegate {
    func loginDidComplete() {
        print("login did complete")
        backToAccountView()
    }
    
    func logoutDidComplete() {
        print("logout did complete")
        backToAccountView()
    }
}

extension LoginViewController {
    
    func backToAccountView() {
        guard let vc = AccountModule.build() as? AccountViewController else {
            return
        }
        print("user: \(ssLoginManager?.getUser())")
        vc.modalPresentationStyle = .overFullScreen
        present(vc, animated: true, completion: nil)
    }
}

extension LoginViewController: LoginViewProtocol {
    
}
