//
//  AccountDetailModule.swift
//  SShop
//
//  Created Nguyen Xuan on 3/6/20.
//  Copyright © 2020 Nguyen Xuan. All rights reserved.
//
//  Template generated by LinhVT - @linh.deli
//

import UIKit

class AccountDetailModule: AccountDetailBuilderProtocol {
    
    static func build() -> UIViewController {
           // Change to get view from storyboard if not using progammatic UI
           let view = AccountDetailViewController(nibName: nil, bundle: nil)
           let interactor = AccountDetailInteractor()
           let router = AccountDetailRouter()
           let presenter = AccountDetailPresenter(view: view, interactor: interactor, router: router)
           
           view.presenter = presenter
           interactor.presenter = presenter
           router.viewController = view
           
           return view
       }
}
