//
//  AccountDetailPresenter.swift
//  SShop
//
//  Created Nguyen Xuan on 3/6/20.
//  Copyright © 2020 Nguyen Xuan. All rights reserved.
//
//  Template generated by LinhVT - @linh.deli
//

import UIKit

class AccountDetailPresenter: AccountDetailPresenterProtocol {
    weak private var view: AccountDetailViewProtocol?
    var interactor: AccountDetailInteractorProtocol?
    private let router: AccountDetailWireframeProtocol

    init(view: AccountDetailViewProtocol, interactor: AccountDetailInteractorProtocol?, router: AccountDetailWireframeProtocol) {
        self.view = view
        self.interactor = interactor
        self.router = router
    }

}
