//
//  AccountDetailProtocols.swift
//  SShop
//
//  Created Nguyen Xuan on 3/6/20.
//  Copyright © 2020 Nguyen Xuan. All rights reserved.
//
//  Template generated by LinhVT - @linh.deli
//

import Foundation

// MARK: - Builder
protocol AccountDetailBuilderProtocol: class {

}

// MARK: - Wireframe
protocol AccountDetailWireframeProtocol: class {

}

// MARK: - Presenter
protocol AccountDetailPresenterProtocol: class {

}

// MARK: - Interactor
protocol AccountDetailInteractorProtocol: class {
    var presenter: AccountDetailPresenterProtocol?  { get set }
}

// MARK: - View
protocol AccountDetailViewProtocol: class {
    var presenter: AccountDetailPresenterProtocol?  { get set }
}
