//
//  AccountDetailInteractor.swift
//  SShop
//
//  Created Nguyen Xuan on 3/6/20.
//  Copyright © 2020 Nguyen Xuan. All rights reserved.
//
//  Template generated by LinhVT - @linh.deli
//

import UIKit

class AccountDetailInteractor: AccountDetailInteractorProtocol {
    weak var presenter: AccountDetailPresenterProtocol?
}
