//
//  LoginProtocols.swift
//  SShop
//
//  Created Nguyen Xuan on 3/11/20.
//  Copyright © 2020 Nguyen Xuan. All rights reserved.
//
//  Template generated by LinhVT - @linh.deli
//

import Foundation

// MARK: - Builder
protocol LoginBuilderProtocol: class {

}

// MARK: - Wireframe
protocol LoginWireframeProtocol: class {

}

// MARK: - Presenter
protocol LoginPresenterProtocol: class {

}

// MARK: - Interactor
protocol LoginInteractorProtocol: class {
    var presenter: LoginPresenterProtocol?  { get set }
}

// MARK: - View
protocol LoginViewProtocol: class {
    var presenter: LoginPresenterProtocol?  { get set }
}
