//
//  LoginPresenter.swift
//  SShop
//
//  Created Nguyen Xuan on 3/11/20.
//  Copyright © 2020 Nguyen Xuan. All rights reserved.
//
//  Template generated by LinhVT - @linh.deli
//

import UIKit

class LoginPresenter: LoginPresenterProtocol {
    weak private var view: LoginViewProtocol?
    var interactor: LoginInteractorProtocol?
    private let router: LoginWireframeProtocol

    init(view: LoginViewProtocol, interactor: LoginInteractorProtocol?, router: LoginWireframeProtocol) {
        self.view = view
        self.interactor = interactor
        self.router = router
    }
        
    func preformLogin(_ view: UIViewController, with service: LoginService) {
        SLoginManager.shared.login(from: view, with: service)
    }
    
    func loginCompleted() {
        router.backToAccountScence()
    }
    
    func closeTapped() {
        router.backToAccountScence()
    }
}
