//
//  LoginProtocols.swift
//  SShop
//
//  Created Nguyen Xuan on 3/11/20.
//  Copyright © 2020 Nguyen Xuan. All rights reserved.
//
//  Template generated by LinhVT - @linh.deli
//

import UIKit

enum LoginService: String {
    case facebook
    case google
}

protocol LoginManagerDelegate {
    func loginDidComplete()
    func logoutDidComplete()
}

// MARK: - Builder
protocol LoginBuilderProtocol: class {

}

// MARK: - Wireframe
protocol LoginWireframeProtocol: class {
    func backToAccountScence()
}

// MARK: - Presenter
protocol LoginPresenterProtocol: class {
    func preformLogin(_ view: UIViewController, with service: LoginService)
    func loginCompleted()
    func closeTapped()
}

// MARK: - Interactor
protocol LoginInteractorProtocol: class {
    var presenter: LoginPresenterProtocol?  { get set }
}

// MARK: - View
protocol LoginViewProtocol: class {
    var presenter: LoginPresenterProtocol?  { get set }
}
