//
//  LoginInteractor.swift
//  SShop
//
//  Created Nguyen Xuan on 3/11/20.
//  Copyright © 2020 Nguyen Xuan. All rights reserved.
//
//  Template generated by LinhVT - @linh.deli
//

import UIKit

class LoginInteractor: LoginInteractorProtocol {
    weak var presenter: LoginPresenterProtocol?
}
